name: Robot Framework - Python
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y xvfb
          sudo apt-get install -y libnss3 libgconf-2-4
          sudo apt-get install -y libxss1
          sudo apt-get install -y fonts-liberation
          sudo apt-get install -y libappindicator1
          sudo apt-get install -y libindicator7
          sudo apt-get install -y wget

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-pabot  # Optional: for parallel test execution

      - name: Start Xvfb
        run: |
          sudo Xvfb :99 -ac &
        env:
          DISPLAY: :99

      - name: Test with RobotFramework
        run: |
          robot --variable BROWSER:headlesschrome .

      - name: Create results directory and move report
        run: |
          mkdir -p results
          mv report.html results/
   
      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Report
          path: results/  # Ensure this path is correct based on where your reports are generated
